# Generated by Django 4.1.3 on 2022-11-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('skin_type', models.CharField(choices=[('OILY SKIN', 'OILY SKIN'), ('DRY SKIN', 'DRY SKIN'), ('NORMAL SKIN', 'NORMAL SKIN')], max_length=15, verbose_name='Skin Type')),
                ('solution', models.TextField(max_length=10000, verbose_name='Solution')),
            ],
        ),
    ]
